### ISSUE TITLE
Patch revision increment case

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#10]
With current [versioning policy](https://github.com/SitecoreSupport/Readme/blob/master/VERSIONING.md) it is not clear whether revision must be reset when porting patch to another product version or not. For example:

Branch        | Release/Tag 1 | Release/Tag 2
------------- | ------------- | -------------
v8.1.3        | 8.1.3.0       | 8.1.3.1      
v8.2.0        | 8.2.0.2       | 8.2.0.3      

vs 

Branch        | Release/Tag 1 | Release/Tag 2
------------- | ------------- | -------------
v8.1.3        | 8.1.3.0       | 8.1.3.1      
v8.2.0        | 8.2.0.0       | 8.2.0.1

**Comment by AlenPelin** [comment]
@olegburov @RomanChernyk your opinion here?

**Comment by olegburov** [comment]
In my opinion, we should use only the second variant. A patch iteration must be started from `0` every time when major or minor or update version is changed.

There could be a situation when a new branch `8.2.0` is created based on `8.1.3`, where the latest changes of release/tag `8.1.3.1` sit. This situation can be tracked using [Graphs/Network](https://help.github.com/articles/about-repository-graphs/#network) feature.

**Comment by AlenPelin** [comment]
Agree, lets keep it as simple as possible.
