### ISSUE TITLE
Add details about patch compatibility

### ISSUE THREAD

**Issue by RomanChernyk** [SitecoreSupport/Readme#11]
We need the instructions about how to apply the patch on the product versions other than that specified in the **Compatibility** section of the release and how to extend the patch compatibility.

**Comment by RomanChernyk** [comment]
Done. @AlenPelin, please check:
https://github.com/SitecoreSupport/Readme/blob/master/PATCH.md#6-patch-compatibility

**Comment by AlenPelin** [comment]
Looks good.
