### ISSUE TITLE
Issues with .NET 4.5.2

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#13]
Currently some .NET 4.5.2 patches cannot compile on build server due to missing .NET 4.5.2 Developer Pack according to https://support.microsoft.com/en-us/kb/2971005

IT is working on fixing the issue. ETA ASAP.

Patches affected:
* https://github.com/SitecoreSupport/Sitecore.Support.137518

**Comment by RomanChernyk** [comment]
Looks like this is fixed now.
