### ISSUE TITLE
Update KB guidelines to publish patches through the github

### ISSUE THREAD

**Issue by RomanChernyk** [SitecoreSupport/Readme#14]

**Comment by RomanChernyk** [comment]
Ensure to mention that there should be a strict one-to-one mapping between “applies to” field on KB and “The release was built for and tested with” on GitHub, unless there is a specific reason to do otherwise.

**Comment by AlenPelin** [comment]
It is about internal guidelines of creating KB that refers to GitHub.

**Comment by RomanChernyk** [comment]
Updated. Under review now.
