### ISSUE TITLE
Simple cumulative patch

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#19]
Update readme with simple cumulative patch rules - several IDs.

**Comment by RomanChernyk** [comment]
Updated. Please check step 6:
[https://github.com/SitecoreSupport/Readme/blob/master/README.md](https://github.com/SitecoreSupport/Readme/blob/master/README.md)

**Comment by AlenPelin** [comment]
Looks good. I've just added this part

> **Note** the TFS IDs must be sorted ascending, for example: Sitecore.Support.12345.22222.99999

to avoid situation when same set of issues is fixed several time. I also registered PatchCreator/issues/16 to enforce this rule.
