### ISSUE TITLE
Add TheCore article about GitHub

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#20]
Add TheCore article about GitHub usage:
* follow /readme for creating patches
* what to do if github is unavailable

**Comment by RomanChernyk** [comment]
I've updated our Patch Guidelines with the requirement to use Patch Storage on GitHub:
http://thecore.dk.sitecore.net/Enablement/PSS/Technical-support/Resources/Patch%20guidelines.aspx
I left the "Creating patch using Visual Studio" section for the situations when there any issues with Patch Storage or related sowtware.

I didn't mention the backup storage. I think we can just announce it by e-mail at the day when something happens to GitHub. Hope, this day never happen.

@AlenPelin Please let me know whether you find this ok.

**Comment by AlenPelin** [comment]
@RomanChernyk looks good. Agree, lets keep it a secret for now.
