### ISSUE TITLE
Patch description mess

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#28]
I propose to completely remove issue description/explanation from the repository as it does not really necessary (main value is versioning and installation instructions) and at the moment we don't have technical writers reviewing them. So we either remove this ability or do something to make them look professional.

**Comment by AlenPelin** [comment]
@developers

**Comment by AlenPelin** [comment]
@RomanChernyk @SC-AFI @olegburov

**Comment by RomanChernyk** [comment]
Vote for removing.

**Comment by SC-AFI** [comment]
I think that:
1. the description of a repository should be left;
-- It allows ensuring the purpose of the patch one more time. 
2. the description of a release should be removed.

**Comment by AlenPelin** [comment]
Well, if everything goes as in plan, it doesn't matter. But agree with @SC-AFI as it is easier to find what you need without comparing those digits, and because currently description is stored in different places and engineers tend to modify it in release forgetting about master branch.

**Comment by olegburov** [comment]
Vote for keeping. Moreover, I would extent it with two required sections:

- What an issue is or why there is an issue
- How a patch fixes it

**Comment by AlenPelin** [comment]
1. It is not easy to describe how patch fixes issue. 
2. I still think that it is a good idea to remove patch description from releases to make it consistent 
3. Even more, it may be necessary to either remove description from master branch and leave it only in github repo metadata (on the top of the page) or make it synchronize these two.

**Comment by RomanChernyk** [comment]
> Vote for removing.

I though we are talking about master branch.

As for the releases - this is a space where an engineer can put anyu details about the patch work. It should be there, I think

**Comment by RomanChernyk** [comment]
Looks like there are too many different opinions here.

Might be better to leave everything as is :)

**Comment by AlenPelin** [comment]
Agree. Postponed.
