### ISSUE TITLE
Introduce signing policy for all shared-source patches

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#3]
We need to introduce signing policy for all shared-source patches in order to prevent possible confuses that may arise if 3rd parties modify original patch source code and re-release with same name and version marks.

**Comment by AlenPelin** [comment]
Currently it is implemented as a part of #4, but we don't have an official policy that it is required. @RomanChernyk @olegburov @ivansharamok @andrew-at-sitecore your thoughts on that?

**Comment by olegburov** [comment]
ARO said that he wanted it to be official policy, which must be published on the Core here: `/Enablement/PSS/Technical-support/Resources/Patch guidelines`

@AlenPelin if a page for a manual signing is ready, we can publish a new rule on the above page.

**Comment by RomanChernyk** [comment]
This is just another rule for an engineer while we have quite a lot already... Not sure we should require doing this manually and publish as a policy.

Rather this should be done by CI once we have an automated patching compilation facilities.

**Comment by AlenPelin** [comment]
Will be discussed internally.
