### ISSUE TITLE
Optional configuration files

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#32]
I propose to make our configuration files even better than in #31 and give extra important points:
* **Sitecore.Support.123456.config** must contain only absolutely necessary configuration changes
* **Sitecore.Support.123456.[OptionalPart].config** must contain optional parts that are not absolutely necessary and can be disabled without patch malfunction

**For example**, if patch fixes something in core database, then 
* **Sitecore.Support.123456.Master.config** for changes in master database (can be disabled on CD)
* **Sitecore.Support.123456.Web.config** for changes in web database (can be disabled on CM)

**Comment by AlenPelin** [comment]
@RomanChernyk @SC-AFI @olegburov

**Comment by RomanChernyk** [comment]
Would be perfect for an ideal world, but in our case looks more like an overcomplication.

**Comment by SC-AFI** [comment]
It looks like we hardly ever have the patches which demand dividing the '*.config' file. Therefore I agree with Roman.

**Comment by AlenPelin** [comment]
Good then.
