### ISSUE TITLE
Change branch naming to 8.1.3.x

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#7]
Current branch and release naming looks as follows:

Branch | Tag 1   | Tag 2 
------ | ------- | -------
v8.1.3 | 8.1.3.0 | 8.1.3.1 
v8.2.0 | 8.2.0.0 | 8.2.0.1 

> Note, in this example both tag and appropriate release have same name

As first tests show, it slightly confuses people. In order to improve clearness and consistency of branch and release names, I suggest to consider using following convention:

Branch  | Tag 1   | Tag 2 
------- | ------- | -------
8.1.3.x | 8.1.3.0 | 8.1.3.1 
8.2.0.x | 8.2.0.0 | 8.2.0.1 

In addition, we can also extend branch name with module version:

Branch        | Tag 1         | Tag 2         
------------  | ------------- | ------------- 
8.1.3.x-3.3.0 | 8.1.3.0-3.3.0 | 8.1.3.1-3.3.0 
8.2.0.x-3.4.0 | 8.2.0.0-3.4.0 | 8.2.0.1-3.4.0

**Comment by AlenPelin** [comment]
Hey @RomanChernyk @olegburov @alexeylunev ... what are your opinions?

**Comment by RomanChernyk** [comment]
I like the last proposal. It will also work well for SXA, for example, which have different packages for different Sitecore versions, while having the same module version:
https://dev.sitecore.net/Downloads/Sitecore_Experience_Accelerator/11/Sitecore_Experience_Accelerator_11_Initial_Release.aspx

**Comment by alexeylunev** [comment]
Hi Alen,

I like the entire idea, however, I'm not sure we need the CMS version be referenced for the module patch. I think having just module version in the patch name should be enough.

**Comment by RomanChernyk** [comment]
If we follow the latest agreement we've made on the meeting, then there is still a need to specify the Sitecore version the patch was tested with, in that case, it makes some sense to keep the Sitecore version in the branch name as well.

This does not mean that you need to create a new branch for each and every Sitecore version. It is still enough to just update the release text if there are no code changes.

Such approach also works well for the modules like SXA as stated above which has the same version with different code base depending on Sitecore version.

**Comment by olegburov** [comment]
@AlenPelin What does `x` stand for in the branch name like `8.1.3.x`?

**Comment by AlenPelin** [comment]
@olegburov it stands for digit in release, it just indicates the releases family; just in case, I suggest to use the 'ex' character in the branch name.

**Comment by olegburov** [comment]
To me adding `x` just to match a release family looks superfluous. `v8.1.3` in a branch name indicates Sitecore's version, while `8.1.3.0` in release indicates a patch's version, where we agreed to use Sitecore's version `<Major>.<Minor>.<Update>.<Patch Iteration>`.

If we decide to extend a branch name policy with a module version, then this `x` will looks really confused. People will start asking should I add it Sitecore's version `8.2.0.x-3.4` or module `8.2.0-3.4.x` / `8.2.0-3.4.0.x` or both `8.2.0.x-3.4.x` / `8.2.0-3.4.0.x`

**Comment by AlenPelin** [comment]
Well, for modules it may make sense to use reverse order in digits:

| Branch | Tag 1 | Tag 2 |
| --  | -- | -- |
| 3.3.0.x-8.1.3 | 3.3.0.0-8.1.3 | 3.3.0.1-8.1.3 |
| 3.4.0.x-8.2.0 | 3.4.0.0-8.2.0 | 3.4.0.1-8.2.0 |

vs

| Branch | Tag 1 | Tag 2 |
| --  | -- | -- |
| v3.3.0-8.1.3 | 3.3.0.0-8.1.3 | 3.3.0.1-8.1.3 |
| v3.4.0-8.2.0 | 3.4.0.0-8.2.0 | 3.4.0.1-8.2.0 |

**Comment by AlenPelin** [comment]
Well, for modules it may make sense to use reverse order in digits:

Branch        | Tag 1         | Tag 2 
------------- | ------------- | ------------- 
3.3.0.x-8.1.3 | 3.3.0.0-8.1.3 | 3.3.0.1-8.1.3 
3.4.0.x-8.2.0 | 3.4.0.0-8.2.0 | 3.4.0.1-8.2.0 

vs

Branch       | Tag 1         | Tag 2 
-----------  | ------------- | -------------
v3.3.0-8.1.3 | 3.3.0.0-8.1.3 | 3.3.0.1-8.1.3 
v3.4.0-8.2.0 | 3.4.0.0-8.2.0 | 3.4.0.1-8.2.0 

For those rare patches that aim 2 and more modules and where versions of modules are differs, we should use module abbrs:

Branch                     | Tag 1                      | Tag 2
-------------------------- | -------------------------- | --------------------------
v8.1.3-exm3.3.0-spif1.2.0 | 8.1.3.0-exm3.3.0-spif1.2.0 | 8.1.3.1-exm3.3.0-spif1.2.0
v8.2.0-exm3.4.0-spif1.2.0 | 8.2.0.0-exm3.4.0-spif1.2.0 | 8.2.0.1-exm3.4.0-spif1.2.0

vs 

Branch                     | Tag 1                      | Tag 2
-------------------------- | -------------------------- | --------------------------
v8.1.3-exm3.3.0-spif1.2.0 | 8.1.3.0-exm3.3.0-spif1.2.0 | 8.1.3.1-exm3.3.0-spif1.2.0
v8.2.0-exm3.4.0-spif1.2.0 | 8.2.0.0-exm3.4.0-spif1.2.0 | 8.2.0.1-exm3.4.0-spif1.2.0

**Comment by AlenPelin** [comment]
During the meeting it was decided to use following format:

Patch for  | Branch        | Tag 1         | Tag 2        
---------- | ------------- | ------------- | -------------
CMS only   | v8.1.3        | 8.1.3.0       | 8.1.3.1 
CMS only   | v8.2.0        | 8.2.0.0       | 8.2.0.1 
1 module   | v3.3.0-8.1.3  | 3.3.0.0-8.1.3 | 3.3.0.1-8.1.3 
1 module   | v3.4.0-8.2.0  | 3.4.0.0-8.2.0 | 3.4.0.1-8.2.0 
2+ modules | Not supported | Not supported | Not supported
