### ISSUE TITLE
Extend readme with info about patches that does not require assembly

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Readme#9]
Add information that in this case assembly is still required to keep track of installed patches. Also you can mention that config file can be deleted if not required.

**Comment by RomanChernyk** [comment]
>> Also you can mention that config file can be deleted if not required.
There is already the following:
`if patch requires changes in configuration, otherwise the entire App_Config folder should be deleted`
https://github.com/SitecoreSupport/Readme/blob/master/PATCH.md#3c-configuration

**Comment by RomanChernyk** [comment]
Done. @AlenPelin please check:
https://github.com/SitecoreSupport/Readme/blob/master/PATCH.md#3d-code

**Comment by AlenPelin** [comment]
Looks good.
